# Generated automatically from Makefile.in by configure.
all nodvi readline.dvi readline.info history.dvi history.info readline.ps history.ps readline.html history.html info dvi ps html text readline.0 clean distclean mostlyclean maintainer-clean installdirs install uninstall:
	
