/* Copyright (c) 1989 by Carrick Sean Casey. All rights reserved. */ 
/* cute sayings when a user hits RETURN with no text */ 
/* Additional sayings by Alaric (c) 1994 */ 
#include <config.h> 
#include "icb.h"
#include "externs.h" 

#ifdef HAVE_LRAND48
#define MYRANDFUNC lrand48()
#else 
#define MYRANDFUNC rand()
#endif

char *prompt[] = { 
"Now I'm going to turn over the next card and I want you to concentrate and tell me what you think it is.",
"All right.  What is it?",
"Now just clear your mind and tell me what you see.",
"Circle?",
"Close -- but definitely wrong.",
"Ready?",
"Well, you're doing great.  Keep it up.",
"Nervous?",
"Yes.  I don't like this.",
"Well, just 75 more to go.  What's this one?",
"You volunteered, didn't you?",
"Aren't we paying you for this?",
"Yeah, but I didn't know you were going to give me electric shocks.",
"What are you trying to prove?",
"I'm studying the effect of negative reinforcement on ESP ability.",
"I'll tell you the effect!  It pisses me off!",
"Then my theory was correct.",
"Well, I guess some people have it and some don't.",
"Definitely.  I think you may be a very gifted telepath.",
"Drop everything, Venkman.  We got one.",
"Excuse me for a minute.",
"Eight o'clock?",
"Spengler and I have charted every psychic occurrence in the Tri-State area for the past two years.",
"The graph we came up with definitely points to something big.",
"Ray, as your friend I have to tell you I think you've really gone around the bend on this ghost stuff.",
"You've been running your ass off for two years checking out every schizo in the Five Boroughs who thinks he's had an experience.",
"And what have you seen?",
"What do you mean by \"seen?\"",
"Looked at with your eyes.",
"Well, I was at an unexplained multiple high-altitude rockfall once.",
"Uh-huh.",
"I've heard about the rockfall, Ray.",
"I think you've been spending too much time with Spengler.",
"Egon?",
"Egon!",
"Oh!  You're here.",
"What have you got, Egon?",
"Oh, this is big, Peter.",
"This is very big. There's definitely something here.",
"Egon, somehow this reminds me of the time you tried to drill a hole in your head.  Do you remember that?",
"Yes.  I'm Dr. Venkman and this is Dr. Stantz.",
"One thing at a time.  We don't even know what it is yet.",
"I don't remember seeing any legs, but it definitely had arms because it reached for me.",
"Well, my uncle thought he was St. Jerome.",
"No.",
"I thought not.  And one last thing.  Are you currently menstruating?",
"Nice.",
"It's here.",
"It looks like a big pair of breasts and a pot belly.",
"It's a woman.",
"Anything!  Just make contact.",
"Ready.",
"Okay...",
"We'll get back to you.",
"Spengler, are you serious about actually catching a ghost?",
"I'm always serious.",
"Egon, I take back everything I ever said about you.  Take this.",
"Yeah, but I introduced you guys.  You never would've met if not for me.  That's got to be worth something.",
"No, we're moving you OFF CAMPUS.  The Board of Regents has decided to terminate your grant.",
"You are to vacate these premises immediately.",
"This is preposterous!  I demand an explanation.",
"Fine.  This University will no longer continue any funding of any kind for your group's activities.",
"But why?  The students love us!",
"Dr. Venkman, we believe that the purpose of science is to serve mankind.",
"You, however, seem to regard science as some kind of \"dodge\" or \"hustle.\"",
"Your theories are the worst kind of popular tripe, your methods are sloppy and your conclusions are highly questionable.",
"You're a poor scientist, Dr. Venkman, and you have no place in this department or in this University.",
"I see.",
"It could be worse, Dr. Venkman.  They took the astronomer Phileas and staked his head to the town gate.",
"You're always so worried about your reputation.",
"We don't need the University.",
"Einstein did his best stuff while he was working as a patent clerk.",
"'They can't stop progress.",
"For what purpose?",
"I don't know.  That costs money.",
"And the ecto-containment system we have in mind will require a load of bread to capitalize.",
"Where would we get the money?",
"You'll never regret this, Ray.",
"You're not going to lose the house.",
"Everybody has three mortgages these days.",
"But at nineteen percent interest!  You didn't even bargain with the guy.",
"Will you guys relax?",
"We are on the threshold of establishing the indispensable defense science of the next decade - Professional Paranormal Investigations and Eliminations.",
"The franchise rights alone will make us wealthy beyond your wildest dreams.",
"But most people are afraid to even report these things.",
"Maybe.  But no one ever advertised before.",
"Besides this, you've got another substantial work area on the ground floor, office space, sleeping quarters and showers on the next floor, and you have your full kitchen on the top level.",
"It's 10,000 square feet total.",
"It's 9,642.55 square feet.",
"What is he -- your accountant?",
"Yes, I know.  What are you calling your business?",
"Ghostbusters.",
"Oh, well, this place is perfect for it.",
"Oh, Dana, it's you ...",
"... I thought it was the drug store.",
"Are you sick, Louis?",
"Oh, no, I feel great.  I just ordered some more vitamins.",
"I see you were exercising. So was I.",
"I taped \"20 Minute Workout\" and played it back at high speed so it only took ten minutes and I got a really good workout.",
"You wanna have a mineral water with me?",
"No thanks, Louis.  I'm really tired.  I've been rehearsing all morning.",
"Okay.  I'll take a raincheck.",
"I always have plenty of mineral water and other nutritious health foods, but you know that.",
"Listen, that reminds me, I'm having a party for all my clients.",
"It's gonna be my fourth anniversary as an accountant.",
"I know you fill out your own tax return, but I'd like you to come being that you're my next door neighbor and all ...",
"Oh, that's nice, Louis.  I'll stop by if I'm around.",
"You know you shouldn't leave your TV on so loud when you go out.",
"That creep down the hall phoned the manager.",
"I thought I turned it off.",
"I climbed on the window ledge to see if I could disconnect the cable but I couldn't reach so I turned up the sound on my TV real loud so they'd think there was something wrong with everybody's TV.",
"You know, you and I should really have keys to each other's apartment ...",
"... in case of emergencies ...",
"What is it?  What's wrong?",
"Look!",
"Gee, there must be a better way.",
"Are you troubled by strange noises in the night?",
"Do you experience feelings of dread in your basement or attic?",
"Have you or your family actually seen a spook, specter or ghost?",
"If the answer is yes, then don't wait another minute.",
"Just pick up the phone and call the professionals -- Ghostbusters.",
"How can we ever thank you?",
"Everybody can relax.  I found the car.  How do you like it?",
"Fourteen hundred.",
"Just needs a little suspension work ... And a muffler ... And maybe brakes.",
"That's very fascinating to me.  I read a lot myself.",
"Some people think I'm too intellectual.",
"But I think reading is a fabulous way to spend your spare time.",
"Is that a game?",
"It's a great game!  You should play sometime.",
"I bet you'd be good.  You seem very athletic.  Do you have any hobbies?",
"I collect spores, molds and fungus.",
"Oh, that's very - unusual.",
"I think it's the food of the future.",
"Remind me not to go to lunch with you.",
"Yes ... well ... I'm not sure.  What I have to say may sound a little ... unusual.",
"We're all professionals here, Miss ...",
"Barrett.  Dana Barrett.",
"Why don't you step into the office and we'll talk about it.",
"What calls?",
"... and then I opened the door again but it was gone.",
"There was nothing there.",
"Generally, you don't see that kind of behavior in a major appliance.",
"What do you think, Egon?",
"Some people like the attention.  Some people are just crazy.",
"Or even a race memory, stored in the collective unconscious.",
"And I wouldn't rule out clairvoyance or telepathic contact either.",
"Is that good?",
"It means you're bright, ambitious, outgoing and very, very sexy,",
"Is that your professional opinion?",
"It's in the stars.",
"Why don't I check out the building?",
"It may have a history of psychic turbulence.",
"Good idea.",
"No, just that one word -- Zuul -- but I have no idea what it means.",
"Spengler,  see if you can find the word \"Zuul\" in any of the literature.",
"I'll take Miss Barrett home and check out her apartment.",
"Have you ever thought of moving out -- at least until this disturbance blows over?",
"No.  If I moved out now I'd be acknowledging that what happened was real.",
"I'm not ready to do that.",
"You play the cello!  It's my favorite instrument.",
"Really?  Do you have a favorite piece?",
"That's a violin concerto.",
"Yeah, but it's got a great cello break.",
"You really don't act like a scientist.",
"No?  What do I act like?",
"Like a used car salesman.",
"Thanks.",
"That's the bedroom, but nothing ever happened in there.",
"What?",
"Nothing.  Is that the kitchen?",
"Well, let's check it out.",
"I'll wait here if you don't mind.",
"I know.  It happened by itself.",
"Nothing.",
"Damn!",
"Yeah, yeah.",
"There's nothing there now and I don't get any significant readings.",
"This is terrible.",
"Either there's a monster in my kitchen or I'm completely crazy.",
"If it's any comfort to you, I don't think you're crazy.",
"I'm a qualified psychologist.",
"I've got a degree and everything.",
"I believe that something happened here and I want to do something about it.",
"All right.  What do you want to do?",
"I think I should spend the night here.",
"On a purely scientific basis.",
"Out!",
"I want to help you.",
"I'll scream.",
"Don't scream.",
"Okay, okay.  But if anything else happens, you have to promise you'll call me.",
"Okay.  Then I'll go.",
"Goodbye.",
"How was your date?",
"It wasn't a date.  It was an investigation.",
"Did you see anything?",
"Didn't see anything,  Didn't get anything. Nice girl - no ghost.",
"I'm starting to worry.",
"You said your graph was pointing to something big.",
"You told me things were going to start popping.",
"They will.",
"Do you know when that might be?",
"We're on the brink of a very serious cash-flow problem.",
"Aren't you glad we waited?",
"I don't know.  It probably would've been the same.",
"What are you doing?  Are you just going to roll over and go to sleep?",
"Roy?  Your clock broke.",
"Nice going, honey.  It was brand new.",
"I didn't break your precious clock, Roy!",
"Now where are you going?",
"To the bathroom, where do you think?",
"Uuuuuuugh!!",
"What did you do in here?  It smells awful!! OH ... Oh, no ... Oh, my God.",
"... right ... It's smelling up the whole suite ... I don't know ... It's just hanging off the ceiling ... I've never seen anything like this ... 1210 ... Quick ...",
"Ghostbusters ... Yes, it is ... Yes, of course they're serious.",
"You do!  You have! Yes, sir.",
"Well, they're out on another case now, but if you'll give me the address",
"... Don't worry, they'll be totally discreet.",
"Has this ever happened before?",
"Well, most of the original staff knows about the twelfth floor ...",
"The disturbances, I mean ... But it's been quiet for years ...",
"Up until two weeks ago ... It was never ever this bad, though.",
"Did you ever report it to anyone?",
"Heavens, no!  The owners don't like us to even talk about it.",
"I hoped we could take care of this quietly tonight.",
"Yes, sir.  Don't worry.  We handle this kind of thing all the time.",
"What are you supposed to be?",
"Me?  We're ... uh ... the exterminators.",
"Somebody saw a cockroach on the twelfth floor.",
"That's gotta be some cockroach,",
"Well, you can't be too careful with those babies.",
"I just realized something.",
"We've never had a completely successful test with any of the equipment.",
"I blame myself.",
"So do I.",
"No sense worrying about it now.",
"We'd better adjust our streams.",
"Yeah, I can smell it.",
"I'm getting high readings near the air vents.",
"It must be using the duct system to get around.",
"See, I told you we'd get something.",
"So far all we got is a shit smell on the twelfth floor and we almost fried a Puerto Rican bellboy.",
"All right.  Let's cool the negative vibes.",
"These things can sense them.",
"When you were in the bathroom, did you notice anything that was yellow and unusually smelly?",
"Ugh!  What a slob!  I'm going to take him.",
"He's getting away!",
"This bites it.  I actually work for a company called Ghostbusters.",
"Sit tight.  I'm on my way.",
"Well, hurry up.",
"How do you know?",
"I don't know.  I'm just guessing.",
"Aagghh -- aaaggghh -- uhh -- uhh -- It slimed me!  It slimed me!",
"Ray!  It's here!  It just went into the Banquet Room on the third floor.",
"Visors down.  Full stream.",
"There!  On the ceiling!",
"What?",
"Why not?",
"Trust me.  It will be bad.",
"What do you mean \"bad?\"",
"It's hard to explain, but try to imagine all life as you know it stopping instantaneously and finding yourself confined forever in another dimension.",
"Now nobody does anything unless I order you to, okay?",
"Let's do it.  This thing's not going to hang around all day waiting for us.  Ray, give me one stream wide right of it. I'll go wide left.  Now!",
"Spengler! A little help!  Cut him off.",
"It's working!",
"Easy ... Easy ... I'm going to throw in my trap now.",
"Easy ... Easy ... Open the trap now!!",
"Watch it ... Watch it ... Now!",
"Are you kidding?  That was like trying to push smoke into a bottle with a baseball bat.  Now what do we do with it?",
"What happened?  Did you see it?  What is it?",
"We got it!",
"What was it?  Will there be any more of them?",
"Sir, what you had there was what we refer to as a focused, non-terminal repeating phantasm or a Class Five Full Roaming Vapor ... A real nasty one, too.",
"Fine.  We'll let it go again.",
"No!  All right.  Anything.",
"Nate Cohen.  I'm with the Post.  What happened in there?",
"Did you really see a ghost?",
"Is this some kind of a stunt?",
"Can we see it?",
"Uh...I'm afraid not.",
"This is not a sideshow!  We're serious scientists.",
"What proof do you have that what you saw was real?",
"Proof?  Well, the manager of the Sedgewick just paid us five big ones to get something out of there.  Is that real enough for you?",
"Are you saying that ghosts really exist?",
"Mister!  Hey, Mister!  Come here!  Mister.",
"Hey, Mister!  Can I see those guns?",
"They're not guns.  They're particle throwers.",
"Yeah, yeah.  I just want to see 'em.",
"I couldn't do that.  You might hurt someone.",
"Wait!  Wait!  Let me ask you something.  If you like shot Superman with those guns, would he feel it or what?",
"Wow!",
"Sing the song from your commercial.",
"There's a thought.  Hit it, Ray.",
"Hello, America.  This is Ronald Gwynne reporting from United Press International in New York.  Throughout my entire career as a journalist I have never reported anything as exciting and incredible as the trapping of an actual supernatural entity by a team of men based in this city who call themselves Ghostbusters.",
"Now, most of us have never even heard of a floating, slime-like substance called ectoplasm, but these gentlemen claim we will be seeing a lot more of it than ever before.",
"Good morning.  Today the entire Eastern Seaboard is alive with talk of hundreds of reported incidents involving multiple sightings in what can only be described as extreme events of paranormal extraphenomenical proportions.  It seems everybody is willing to bring their old ghosts and skeletons out of the closet.  Roy Brady reports from New York.",
"Thank you, Roger.  Everybody's heard ghost stories around the campfire.  Heck, my grandma used to spin yarns about a spectral locomotive that used to rocket past the farm where she grew up.  Now, as if some unseen authority had suddenly given permission, thousands of people here are talking about encounters they claim to have had with ghosts.",
"Ray, every time I hear about your company, I can't help thinking about the old Bob Hope movie.",
"Actually, Joe, the title of that film was \"Ghostbreakers,\" and Olsen and Johnson did one called \"Ghost Catchers\" and the Bowery Boys did \"Ghost Chasers,\" \"Hold That Ghost,\" \"Spooks Run Wild,\" \"Spook Busters,\" and \"Spook Chasers.\"",
"Well, in any case, I guess there's one big question on everybody's mind and you're certainly in a position to answer it for us: Have you seen Elvis and how is he?",
"Our phone-in topic today: Ghosts and Ghostbusting.  The controversy builds as more sightings are reported and some maintain that these professional paranormal eliminators in New York are the cause of it all.  Why did everything start just when these guys went into business?",
"Should they be allowed to carry around unlicensed proton mass drivers?  And what's wrong with ghosts anyway?  Call us ... All our lines are open.  Hello, Larry King.",
"Hello, Larry?  I think what Dr. Spengler said in his interview with you last night was true.  The world is in for a \"psychic shock\" 'cause like my aunt reads coffee grounds and she ...",
"Great rehearsal.",
"You heard it?",
"You're the best one in your row.",
"I don't have to take abuse from you.  I have other people dying to give it to me.",
"I know.  You're quite a celebrity these days.  Are you here because you have info ... about my case?",
"The \"stiff?\"  He happens to be one of the finest musicians in the world and a wonderful man.",
"Is he dying or something?",
"He is a very close friend.  Do you have some explanation of what happened in my apartment?",
"Yes, but I have to tell you in private at a fine restaurant.",
"Can't you tell me now?",
"I'll cancel the reservation,  I found the name \"Zuul\" in ...",
"You must have gotten the last copy.",
"Well, the name Zuul refers to a demi-god worshipped around 6000 B.C. by the ... What's that say?",
"Hittites,  the Mesopotamians and the Sumerians.  \"Zuul was the Minion of Gozer.\"",
"\"Gozer\" -- he was very big in the Sumerian religion.  One of their gods.",
"What's he doing in my refrigerator.",
"I'm checking on that.  I think we should meet Thursday night at nine to talk about it.",
"I don't think so.  I'm busy Thursday night.",
"I'll pick you up at your place.  I'll bring along the Roylance Guide -- we can read after we eat.",
"I've got to go now.",
"Remember.  I'm the only one standing between you and a heavy Hittite.",
"Oh, he's an old professor of mine.",
"Yes.  He's smarter than he looks.",
"Let me ask you something.  The ad in the paper just said \"Help Wanted.\"  What's the job?",
"I really don't know, Mr. Zeddemore.  They just told me to take applications and ask you these questions.",
"Not really.  However, if there's a semi-regular paycheck in it I'll believe anything you say.",
"I can't take much more of this.  The pace is killing me.",
"Here's the paper on the Brooklyn job.  She paid with a Visa card.",
"And this is Winston Zeddemore.  He came about the job.",
"Hi.  Ray Stantz.  Pete Venkman.",
"The EPA?  What's he want?",
"I didn't ask him.  All I know is that I haven't had a break in two weeks and you promised you'd hire more help.",
"Oh, really?  Well, I've quit better jobs than this one, believe me.",
"Very impressive resume.  Electronic countermeasures, Strategic Air Command ... Black belt in Karate ... Small arms expert ... Mr. Zeddemore, as you may have heard, we locate ghosts and spirits, trap them with streams of concentrated quantum energy and remove them from people's homes, offices and places of worship.",
"Yeah, I heard that.  Now tell me what you really do.",
"Can I help you?",
"Are you Peter Venkman?",
"Yes, I'm Doctor Venkman.",
"Exactly what are you a doctor of, Mr. Venkman?",
"I have Ph.D's in psychology and parapsychology.",
"I see.  And now you catch ghosts?",
"You could say that.",
"And how many ghosts have you caught, Mr. Venkman?",
"I'm not at liberty to say.",
"And where do you put these ghosts once you catch them?",
"In a storage facility.",
"And would this storage facility be located on these premises?",
"Yes, it would.",
"And may I see this storage facility?",
"No, you may not.",
"And why not, Mr. Venkman?",
"Because you didn't say the magic word.",
"The magic word is \"please.\"",
"May I please see the storage facility?",
"Why do you want to see it?",
"Well, because I'm curious.  I want to know more about what you do here.  Frankly, there have been a lot of wild stories in the media and we want to assess any possible environmental impact from your operation. For instance, the storage of noxious, possibly hazardous waste materials in your basement.  Now either you show me what's down there or I come back with a court order.",
"Neutronize.  System shut.",
"I've got to sleep.",
"I need two new purge valves.  How's the grid around the storage facility holding up?",
"I'm worried, Ray.  It's getting crowded in there.  And all my recent data points to something big on the bottom.",
"Well, let's say this Twinkie represents the normal amount of psychokinetic energy in the New York area.  According to this morning's PKE sample, the current level in the city would be a Twinkie 35 feet long weighing approximately six hundred pounds.",
"That's a big Twinkie.",
"We could be on the verge of a fourfold crossover ... or worse.  If what we're seeing indicates a massive PKE surge, we could experience an actual rip.",
"Egon, how's the grid around the storage facility holding up?",
"It's not good, Pete.",
"Tell him about the Twinkie.",
"Oh, Dana, it's you.",
"Hi, Louis.",
"Hey, it's crazy in here.  You're missing a classic party.",
"Well, actually Louis I have a friend coming by.",
"Great!  Bring her, too.  But you better hurry.  I made nachos with non-fat cheese and they're almost gone.  I'll make some more though.",
"I got the Twister game for later ...",
"Hello ... Oh, hi Mom.  Yes ... yes. Everything's fine.  No ... nothing.  Just that one time ... I am ... I will ... I won't ... Mother!  I'm all right.  I told you.  Everything's fine ...!  All right. I'll talk to you tomorrow ... I promise. 'Bye.",
"Oh, shit!",
"Louis, do you have any Excedrin or Extra Strength Tylenol?",
"I have acetacylasilic acid but generic from Walgreens cause I can get 600 tables for 35% less than the cost of 300 name brand.  Is it a headache?",
"That's Nova Scotia salmon.  The real thing. It costs $24.95 a pound but really $12.48 a pound net after tax.  I'm writing this whole party off as a promotional expense.  That's why I invited clients instead of friends. Try that Brie, it's dynamite at room temperature.  Maybe I should turn the heat up a bit ...",
"C'mon Louis, maybe if we dance other people will start.",
"Everybody, this is Ted and Annette Fleming. Ted has a small carpet cleaning business in receivership, but Annette is drawing a salary from a deferred bonus from two years ago and the house has $15,000 left at eight percent.",
"Okay.  Who brought the dog?",
"Help! Help!  There's a bear loose in my apartment.",
"I think you're right about Central America but I completely disagree about the other thing.  A good heavyweight boxer could take a Karate guy every time.",
"That is one speedy mutt.",
"He's a big one.  You don't want to mess with that particular breed.",
"Definitely some sort of fighting Spaniel, I think.",
"Hey!  He pulls the wagon.  I make the deals. You wanna ride?",
"No, I'm the Governor of New Jersey.  Now get outta here.",
"What's going on?",
"Some moron brought a cougar to a party and it went berserk,",
"Oh.",
"Hi.",
"Are you the Keymaster?",
"Not that I know of.",
"I am Zuul.  I am the Gatekeeper.",
"I think we better get out of here.",
"We must prepare for the coming of Gozer.",
"He is the Destructor.",
"Really?  Can't wait to meet him.",
"Take me now.",
"Well, I make it a rule never to sleep with possessed people.",
"I am Zuul.  I am ...",
"Right ... You're the Gatekeeper.  But I want Dana.  Dana, speak to me ...",
"Hey man.  What is it you're so involved with there?",
"Uh ... Oh these are blueprints of the structural ironwork in Dana Barrett's apartment building ... And they're most unusual.",
"Me, too.",
"Do you believe in God?",
"No.  But I liked Jesus' style.",
"Me, too. Parts of the Bible are great.",
"Ray, do you remember something in the Bible about a day when the dead would rise up from their graves?",
"Right.  And the sky would fall ...",
"Judgement Day ...",
"Yeah, Judgement Day.",
"Every ancient religion had its own myth about the end of the world.",
"Well, has it ever occurred to you that the reason you've been so busy lately is because the dead have been rising from their graves?",
"Evening.  We've had a problem here for quite some time.  I called your outfit a couple of weeks ago.",
"Busy time of year.",
"Nobody likes to talk about this sort of thing.",
"You don't have to worry about that with us, sir.",
"Right.  We'll believe anything.",
"You check the armory.  I'll go down to the officers' barracks.",
"We picked up this guy and now we don't know what to do with him, Bellevue doesn't want him and I'm afraid to put him in the lock-up.  I'm telling you, there's something weird about him.  And I know you guys are into this stuff so we figured we'd check with you.",
"Bring him inside, Officer.",
"I am Vinz Clortho - Keymaster of Gozer.",
"Oh, no.  Tully is the fleshbag I'm using. I must wait inside for the sign.",
"Do you want some coffee while you're waiting?",
"Yes, have some.",
"Gozer the Traveller will come in one of the pre-chosen forms.  During the rectification of the Vuldronaii the Traveller came as a very large and moving Torb.  Then of course in the third reconciliation of the last of the Meketrex supplicants they chose a new form for him, that of a Sloar.  Many Shubs and Zuuls knew what it was to be roasted in the depths of the Sloar that day I can tell you.",
"Hello?",
"It's Peter, Egon.  I've got a problem.",
"What is it?",
"I'm with Dana Barrett and she's floating three feet off the bed.",
"Does she want to be?",
"I don't think so.  It's more of that Gozer thing.  She says she's the Gatekeeper.  Does that make any sense to you?",
"Some.  I just met the Keymaster.  He's here with me now.",
"Yeah, yeah.  I was just thinking.  It probably wouldn't be a good idea for them to get together at this point.",
"I agree.",
"You have to keep him there.  Do whatever you have to, but don't let him leave,  He could be very dangerous.",
"I'll spend the night here and get back first thing in the morning.",
"All right, Peter.  Good night.",
"Die in what sense?",
"In the physical sense.",
"I don't care.  I see us as tiny parts of a vast organism, like two bacteria living on a rotting speck of dust floating in an infinite void.",
"That's so romantic.",
"Stantz?  You okay in there?",
"Step aside, Miss, or I'll have you arrested for interfering with a police officer.",
"If you turn that thing off we won't be responsible for the consequences.",
"On the contrary!  You will be held completely responsible.",
"I've never seen anything like this before. I don't know ...",
"If he tries that again, shoot him.",
"Thank you, Officer.",
"It is time.  This is the sign.",
"It's a sign, all right ... \"Going Out Of Business.\"",
"... does it contain TCE, PCB or tailings from styrene esters or any polyfluoric groups...?",
"What are the pink particles?  What will happen if we use water?",
"No ... no water.  There's nothing you can do.",
"Did you have any kind of solvents or any concentrated sulphurs of any kind?",
"What happened??!!!?",
"The storage facility blew.  This one ...",
"If you don't shut up I'm going to rip out your septum.",
"Gulf and Western Building!  And I'm in a hurry so let's not dawdle.",
"Are you the Gatekeeper?",
"Come on.  You want me to stick you?  Come on.",
"I am Vinz Clortho.  I am the Keymaster.  Do you bar my way?",
"Are you crazy, man?  You don't give, Jino's gonna rip you, man.  Nobody gets by Jino.",
"Yeah.  We bar your way.",
"And look at this, Peter",
"No!  Nobody ever built them like this!  The architect was either an authentic whacko or a certified genius.  The whole building is like a huge antenna for pulling in and concentrating psychokinetic energy.",
"Who was the architect?",
"He's listed on the blueprints as I. Shandor.",
"Yes.  After the First World War Shandor decided that society was too sick to survive.  And he wasn't alone.  He had close to a thousand followers when he died.  They conducted rituals, bizarre rituals, intended to bring about the end of the world.",
"Who?",
"Gozer.",
"Get a grip on yourself, Egon.  I talked to Dana Barrett and she referred to Gozer as the Destructor.",
"This is insane!  You actually believe that some moldy Babylonian God is going to drop in at 78th and Central Park West and start tearing up the city?",
"Are you the Ghostbusters?",
"What about it?",
"The  mayor wants to see you -- right away. The whole island is going crazy.  Let's go.",
"The man is a psychopath, Your Honor.",
"Probably a mixture of gases, no doubt stolen from the Army ...",
"Bullshit!!!",
"... improperly stored and touched off with those high-voltage laser beams they use in their light show.  They caused an explosion.",
"All I know is, that wasn't a light show we saw this morning.  I've seen every form of combustion known to man, but this beats me.",
"And nobody's using nerve gas on all the people that have seen those ... things ... all over the city.  The walls were bleeding at the 53rd Precinct.  How do you explain that?",
"Officially, the Church will not take a position on the religious implications of these ... phenomena.  However, since they started, people have been lining up at every church in the city to confess and take communion.  We've had to put on extra priests.  Personally, I think it's a sign from God but don't quote me on that.",
"I'm Winston Zeddemore, Your Honor.  I've only been with the company for a couple of weeks, but I gotta tell you -- these things are real.  Since I joined these men I have seen shit that would turn you white.",
"Mr. Mayor, it's a pretty simple choice. You can believe Mr. Pecker here ...",
"What do you mean \"Biblical?\"",
"Old Testament, Mr. Mayor.  \"Wrath of God\"-type stuff.  The seas could boil, fire and brimstone falling from the sky ...",
"Enough!  I get the point.",
"If I'm wrong then nothing happens and you toss us in the can.  But if I'm right, and if we can stop this thing ... well, let's just say that you could save the lives of a lot of registered voters.",
"Get him out of here.",
"Louis!  What are you doing standing there ... get out of the building ... don't you know it's an earthquake or something?",
"The Traveller is coming.",
"Don't be crazy.  Nobody is going to come and visit you with all this commotion going on.",
"I don't understand it,  Why here?   Why now?",
"What goes around, comes around, Mr. Mayor. The big Lazy Susan of Karma just keeps turning and sometimes we get the short end of the stick.",
"This may be Nature's way of telling us to slow down.  You have to admit it's kind of humbling, isn't it?",
"We've cleared the whole building and cordonned off the street.  I'm massing our own special tactics squad and the National Guard is on standby.",
"I better alert the Red Cross, too.",
"What is it?",
"It's a souvenir from the 1964 World's Fair at Flushing Meadow.  It's my lucky coin.",
"I don't believe in luck.",
"Keep it anyway.  I have another one at home.",
"Thank you.",
"Okay.  Just remember, whatever happens out there, we are total professionals.  Not only are we the best Ghostbusters around, we're the only Ghostbusters around.  It's up to us.",
"I'm going to make a note of your suggestion and possibly bring it up later if this thing really gets out of hand.  Now let's move.",
"Get 'em! All right, Ghostbusters!",
"I've heard of underground parking but this is ridiculous.",
"Dana?",
"Maybe we should go downstairs and call first?",
"No!  The kitchen!",
"I thought he died!",
"It doesn't seem to have slowed him down any.",
"I don't think it's Shandor.",
"Gozer the Gozerian?",
"Are you a god?",
"Then die!",
"Agile bastard, isn't he?",
"Forget the trapping!  Just blast him!",
"SUBCREATURES!  GOZER THE GOZERIAN, GOZER THE DESTRUCTOR, VOLGUUS ZILDROHAR, THE TRAVELLER HAS COME.  CHOOSE AND PERISH.",
"What's he talking about?  Choose what?",
"CHOOSE!!",
"I think he's saying that since we're about to be sacrificed anyway, we get to choose the form we want him to take.",
"You mean if I stand here and concentrate on the image of Roberto Clemente, Gozer will appear as Roberto Clemente and wipe us out?",
"That appears to be the case.",
"The choice is made.  The Traveller has come.",
"No.",
"My mind's a total void!",
"It's ... It's ... It's the STAY-PUFT MARSHMALLOW MAN.",
"AND YOU CAME UP WITH THAT?",
"The Stay-Puft Marshmallow Man!  He was on all the packages we used to buy when I was a kid.  We used to roast Stay-Puft marshmallows at Camp Waconda!",
"Great!  The marshmallows are about to get their revenge.",
"What now?",
"I want you to go up on the roof and arrest them.  This time they've gone too far.",
"Good.  Now we made him mad.",
"Life is just a state of mind.",
"But it's my favorite state.",
"Either way we're history.",
"Everybody okay?",
"Are you all right?",
"Nothing!  We just got rid of that thing in your kitchen.",
"Really!  Is it gone?",
"Yeah, along with most of your furniture and a lot of your personal possessions.  This one took some work.",
"This is going to cost you, you know.  Our fees are ridiculously high.",
"Talk to my accountant.",
"Oh, great!  I bet we could write off all the damage as an Act of God.",
"I'll go along with that.",
"Well, that definitely looks like marshmallow to me.",
"You have to wonder why anybody would dump a marshmallow that size right in the middle of the street.",
"I wonder if there might not be a very large cup of hot chocolate somewhere in the area.",
"That would definitely explain it.",
"whirred.",
"You suck.",
"You are dumb.",
"People with glasses are ugly nerds.",
"The letter U and the numeral 2.",
"Yo momma'z got an afro, with a chin strap.",
"Hello; my name is Inigo Montoya.  You killed my father; prepare to die.",
"Ho hum.",
"I geek, therefore I am.",
"This is, of course, impossible.",
"Woop",
"w00p w00p iz dah disk0 kall",
"Sorry Dave, I'm afraid I can't do that.",
"That must be some twinkie.",
"Print is dead.",
"There is corrosion on the load bearing members of this building.",
"That would be bad.",
"He slimed me.",
"That must be some cockroach.",
"Hurry up, I don't want babies using ICB.",
"type cookie, you idiot.",
"have you been smoking the wrong color crack?",
"we make pants, word.",
"I hope you don't screw like you type.",
"cuz you'z afloatin n imm about 2 flush yo ass.",
"die alaric die",
"blah",
"what was I doing?",
"I'm so bare!",
NULL
};


saysomething() {
	static int lastprompt = 0;
	static int *cutewords;

	static int linesused;
	int randomone;
	int i;
	/* initialize array bounds */
	if (lastprompt == 0) {
		while (prompt[lastprompt++] != NULL);
		lastprompt--;
		cutewords=(int *) malloc(sizeof(int)*lastprompt);
		for(i=0;i<lastprompt;i++) 
			cutewords[i]=0;
		linesused=0;
	}


	/* pick a line we haven't already used */

	if (linesused==lastprompt) {
		for(i=0;i<lastprompt;i++) 
			cutewords[i]=0;
		linesused=0;
	}
	linesused++;
	randomone=MYRANDFUNC % lastprompt;
	while (cutewords[randomone]==1) {
		randomone=MYRANDFUNC % lastprompt;
	}
	cutewords[randomone]=1;
	/* print a random line from the list above */
	putl(prompt[randomone], PL_SCR);
}
